/**
 * LLM-judgment risk-signal generation (Story 2.2, Phase 2, FR8, AD-8).
 *
 * Computes the qualitative `'llm-judgment'` `RiskSignal` Phase 1 made room
 * for but never produced: one sentence naming a Node's chief risk factor,
 * generated by the same local/cloud backend already used for one-line
 * summaries (Story 1.5/1.6).
 *
 * Deliberately reuses `summary-generator.ts`'s infrastructure rather than
 * standing up a second one (Intent, AD-8):
 *  - `SummarizeFn`/`SummarizeOutcome` — a backend-agnostic "call an LLM, get
 *    text back" shape that fits a judgment exactly as well as a summary; a
 *    judgment-specific result type would just be a structural duplicate.
 *  - `sharedSummaryQueue` — the literal same module-singleton `p-queue`
 *    (concurrency 1) `generateSummaries`/`regenerateNodeSummary` already
 *    funnel every local-model call through. That bound exists because a
 *    single local GGUF model instance has no way to run two generations
 *    concurrently — a judgment call is exactly as much "a generation against
 *    that same loaded model" as a summary call is, so it must serialize
 *    against the identical constraint, not a second one.
 *  - `ensureModelContext` (exported from `summary-generator.ts` this phase)
 *    — the only source of the local model context `createLocalJudge` uses;
 *    never a second `loadModel`/`createContext` call.
 *  - `readNodeSource`/`normalizeSummaryText` — reading a Node's source off
 *    disk and normalizing a model response are identical regardless of
 *    which prompt produced it.
 *
 * `createLocalJudge`/`createCloudJudge` are standalone functions mirroring
 * `createLocalSummarizer`/`createCloudSummarizer` with a different prompt —
 * not parameterized variants of those, which stay entirely untouched (this
 * story's Never constraint) — see this module's own Design Notes framing in
 * the spec for why: small duplication here keeps already-shipped,
 * already-reviewed summary code untouched.
 *
 * Eligibility mirrors `classifyNode`'s own shape but is judgment-specific: a
 * Node is eligible only when its file isn't in the current coverage-gap set
 * AND it has no persisted `NodeRecord.llmJudgment` yet — no regeneration path
 * this phase (Boundaries & Constraints), unlike summaries' Story 1.8 Phase 4
 * `regenerateNodeSummary`.
 *
 * No hardware-advisory tracking (Never constraint — that reactive
 * degenerate-rate nudge is summary-specific, Story 1.5 Phase 3, and recommends
 * switching backends for *summary* generation specifically) and no staleness
 * tracking (Never constraint — judgments have no `detectStaleness`
 * counterpart this phase).
 */

import type { CodeMapNode, LlmJudgmentProgressUpdate } from '@driller/ipc-contracts';
import type {
  getLlama as GetLlama,
  LlamaChatSession as LlamaChatSessionClass,
} from 'node-llama-cpp';
import Anthropic from '@anthropic-ai/sdk';
import type { LocalModelReady } from './model-manager';
import { getNodeRecord, mergeNodeRecord } from './node-record-store';
import {
  ensureModelContext,
  normalizeSummaryText,
  readNodeSource,
  sharedSummaryQueue,
  type SummarizeFn,
  type SummarizeOutcome,
} from './summary-generator';

// Duplicated from `summary-generator.ts`'s own `loadNodeLlamaCppModule`
// (this codebase's established precedent — see that module's and
// `cloud-summary-generator.ts`'s own doc comments — is to duplicate this
// small ESM-only-dependency workaround per module rather than share/export
// it) — node-llama-cpp is ESM-only with top-level await in its own
// dependency graph, so a static import in a module this subprocess's CJS
// bundle `require()`s would throw `ERR_REQUIRE_ASYNC_MODULE` at runtime.
// Cached after the first successful import.
let nodeLlamaCppModule:
  | Promise<{ getLlama: typeof GetLlama; LlamaChatSession: typeof LlamaChatSessionClass }>
  | undefined;

function loadNodeLlamaCppModule(): Promise<{
  getLlama: typeof GetLlama;
  LlamaChatSession: typeof LlamaChatSessionClass;
}> {
  nodeLlamaCppModule ??= import('node-llama-cpp');
  return nodeLlamaCppModule;
}

// Small enough to keep a generated judgment genuinely one sentence, mirroring
// `summary-generator.ts`'s own `SUMMARY_MAX_TOKENS` bound for the same
// reason — an expensive, unbounded generation per Node isn't needed for a
// one-sentence judgment.
const JUDGMENT_MAX_TOKENS = 96;

// Mirrors `summary-generator.ts`'s `SUMMARY_PROMPT_TIMEOUT_MS` — a single
// hung local `session.prompt()` call must not stall this project's entire
// generation forever, for the identical reason that module documents: with
// concurrency fixed at 1 on the shared queue, nothing else can make progress
// behind a truly stuck call.
const JUDGMENT_PROMPT_TIMEOUT_MS = 2 * 60 * 1000;

// Mirrors `cloud-summary-generator.ts`'s own `CLOUD_SUMMARY_TIMEOUT_MS` — a
// bounded overall timeout around one `messages.create` call so a single
// hung/slow request can't stall every remaining Node in the concurrency-1
// queue indefinitely.
const CLOUD_JUDGMENT_TIMEOUT_MS = 3 * 60 * 1000;

// Mirrors `cloud-summary-generator.ts`'s own `CLOUD_MAX_RETRIES` — raised
// above the SDK's own default (2) for the same unattended-batch-run reasoning
// (Always, AD-8).
const CLOUD_MAX_RETRIES = 5;

// Progress batching (Always/AD-8: "never one IPC message per Node") —
// mirrors `summary-generator.ts`'s own `PROGRESS_FLUSH_*` constants.
const PROGRESS_FLUSH_INTERVAL_MS = 1000;
const PROGRESS_FLUSH_BATCH_SIZE = 5;

/**
 * The specific error the local path's `withTimeout` (below) rejects with —
 * mirrors `summary-generator.ts`'s own `SummaryTimeoutError`: a dedicated,
 * checkable subclass rather than a message-text regex.
 */
class JudgmentTimeoutError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'JudgmentTimeoutError';
  }
}

/**
 * The specific error the cloud path's `withTimeout` (below) rejects with —
 * mirrors `cloud-summary-generator.ts`'s own `CloudSummaryTimeoutError`, kept
 * as a distinct type from `JudgmentTimeoutError` for the same reasoning that
 * module documents: a cloud timeout rethrows into the generic catch-and-log
 * path rather than being classified as a `SummarizeOutcome` 'degenerate'
 * result.
 */
class CloudJudgmentTimeoutError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'CloudJudgmentTimeoutError';
  }
}

/**
 * Races `promise` against a timeout — duplicated per-module, matching this
 * codebase's established `withTimeout` precedent (see
 * `summary-generator.ts`/`cloud-summary-generator.ts`'s own copies). Does not
 * cancel the underlying work; it only stops the caller from waiting forever.
 */
function withTimeout<T>(
  promise: Promise<T>,
  ms: number,
  label: string,
  TimeoutErrorCtor: new (message: string) => Error,
): Promise<T> {
  return new Promise<T>((resolve, reject) => {
    const timer = setTimeout(() => {
      reject(new TimeoutErrorCtor(`${label} timed out after ${ms}ms`));
    }, ms);
    promise.then(
      (value) => {
        clearTimeout(timer);
        resolve(value);
      },
      (error: unknown) => {
        clearTimeout(timer);
        reject(error);
      },
    );
  });
}

/**
 * True for the specific error the local path's `withTimeout` throws — a real
 * `instanceof` check, mirroring `summary-generator.ts`'s own
 * `isTimeoutError`.
 */
function isJudgmentTimeoutError(error: unknown): error is JudgmentTimeoutError {
  return error instanceof JudgmentTimeoutError;
}

/**
 * Builds the LLM-judgment prompt (mirrors `summary-generator.ts`'s own
 * `buildPrompt`, `:582`, with a different instruction): one sentence naming
 * the Node's chief risk factor rather than describing what it does.
 */
function buildJudgmentPrompt(node: CodeMapNode, source: string): string {
  return [
    `You are reviewing a codebase for risk. Below is the real source of a ${node.kind.toLowerCase()} named "${node.name}", from ${node.file}.`,
    "Name this code's single chief risk factor — e.g. unclear error handling, tight coupling, missing validation, unbounded growth, or similar — in exactly one concise, plain-language sentence. Do not repeat the code. Do not use markdown. Reply with only the sentence.",
    '',
    'Source:',
    source,
  ].join('\n');
}

/**
 * Builds a `SummarizeFn` backed by the local GGUF model (mirrors
 * `summary-generator.ts`'s own `createLocalSummarizer`, `:661`) — same
 * `LlamaChatSession`-per-job mechanics, driven off the exact same shared,
 * memoized model context via `ensureModelContext` (Always: "the only source
 * of the local model context `createLocalJudge` uses — never a second model
 * load"), just prompted with `buildJudgmentPrompt` instead of `buildPrompt`.
 */
export function createLocalJudge(model: LocalModelReady): SummarizeFn {
  return async (node, projectRoot) => {
    const source = await readNodeSource(projectRoot, node);
    if (source === undefined) {
      return { kind: 'unreadable' };
    }

    const { LlamaChatSession } = await loadNodeLlamaCppModule();
    const { sequence } = await ensureModelContext(model.path);

    const session = new LlamaChatSession({ contextSequence: sequence });
    try {
      let response: string;
      try {
        response = await withTimeout(
          session.prompt(buildJudgmentPrompt(node, source), { maxTokens: JUDGMENT_MAX_TOKENS }),
          JUDGMENT_PROMPT_TIMEOUT_MS,
          `judgment prompt for ${node.id}`,
          JudgmentTimeoutError,
        );
      } catch (error) {
        if (isJudgmentTimeoutError(error)) {
          return { kind: 'degenerate', reason: 'timeout' };
        }
        throw error;
      }
      const text = normalizeSummaryText(response);
      return text.length > 0 ? { kind: 'success', text } : { kind: 'degenerate', reason: 'empty' };
    } finally {
      // Disposes only the session wrapper, not the shared sequence (default
      // `disposeSequence: false`) — the sequence is reused by the next job,
      // including a `generateSummaries` job (both funnel through the same
      // `sharedSummaryQueue`, so they never overlap in practice).
      session.dispose();
    }
  };
}

function buildCloudJudgmentSystemPrompt(node: CodeMapNode): string {
  return [
    `You are reviewing a codebase for risk. Below is the real source of a ${node.kind.toLowerCase()} named "${node.name}", from ${node.file}.`,
    "Name this code's single chief risk factor — e.g. unclear error handling, tight coupling, missing validation, unbounded growth, or similar — in exactly one concise, plain-language sentence. Do not repeat the code. Do not use markdown. Reply with only the sentence.",
  ].join('\n');
}

// Reuses the exact same cloud model `cloud-summary-generator.ts` uses for
// summaries — a judgment is the same class of bulk, short, per-Node cloud
// call as a summary (Design Notes), just with a different prompt; there is
// no reason for judgment generation to be pinned to a different model.
//
// Review round (patch): exported, and `index.ts`'s `startJudgmentGeneration
// ForProject` was using `cloud-summary-generator.ts`'s `CLOUD_SUMMARY_MODEL`
// for the `modelName` it persists into `NodeRecord.llmJudgment.model`
// instead of this constant — harmless today (identical literal value), but
// a latent bug: if either constant is ever changed independently, the
// persisted provenance would silently name the wrong model.
export const CLOUD_JUDGMENT_MODEL = 'claude-sonnet-5';

// Mirrors `cloud-summary-generator.ts`'s own `CLOUD_SUMMARY_MAX_TOKENS` — a
// one-sentence judgment needs no more headroom than a one-sentence summary.
const CLOUD_JUDGMENT_MAX_TOKENS = 256;

/**
 * Calls the Anthropic API for one Node's already-read `source` (mirrors
 * `cloud-summary-generator.ts`'s own `callCloud`) — same
 * authentication/rate-limit classification-for-logging, same rethrow-
 * unchanged-otherwise behavior.
 */
async function callCloudForJudgment(client: Anthropic, node: CodeMapNode, source: string): Promise<string> {
  let response: Anthropic.Message;
  try {
    response = await withTimeout(
      client.messages.create({
        model: CLOUD_JUDGMENT_MODEL,
        max_tokens: CLOUD_JUDGMENT_MAX_TOKENS,
        system: buildCloudJudgmentSystemPrompt(node),
        messages: [{ role: 'user', content: source }],
      }),
      CLOUD_JUDGMENT_TIMEOUT_MS,
      `cloud judgment request for ${node.id}`,
      CloudJudgmentTimeoutError,
    );
  } catch (error) {
    if (error instanceof Anthropic.AuthenticationError) {
      console.error(
        `[graph-service] cloud judgment generation: authentication failed for ${node.id} (check the stored API key): ${error.message}`,
      );
    } else if (error instanceof Anthropic.RateLimitError) {
      console.error(
        `[graph-service] cloud judgment generation: rate limited for ${node.id} after the SDK's own retries: ${error.message}`,
      );
    }
    throw error;
  }

  const textBlock = response.content.find(
    (block): block is Anthropic.TextBlock => block.type === 'text',
  );
  if (!textBlock) {
    console.warn(
      `[graph-service] cloud judgment generation: no text content block in the response for ${node.id} (content block types: ${
        response.content.map((block) => block.type).join(', ') || '(none)'
      }).`,
    );
  }
  return textBlock?.text ?? '';
}

/**
 * Builds a `SummarizeFn` backed by the Anthropic cloud API (mirrors
 * `cloud-summary-generator.ts`'s own `createCloudSummarizer`) — same
 * authentication-short-circuit-after-first-failure behavior, same
 * empty-response-is-'degenerate' classification.
 */
export function createCloudJudge(apiKey: string): SummarizeFn {
  const client = new Anthropic({ apiKey, maxRetries: CLOUD_MAX_RETRIES });
  let authenticationFailed = false;

  return async (node, projectRoot) => {
    const source = await readNodeSource(projectRoot, node);
    if (source === undefined) {
      return { kind: 'unreadable' };
    }

    if (authenticationFailed) {
      throw new Error(
        `Skipping ${node.id}: cloud judgment generation already failed authentication earlier in this run — the stored key won't become valid mid-run.`,
      );
    }

    let response: string;
    try {
      response = await callCloudForJudgment(client, node, source);
    } catch (error) {
      if (error instanceof Anthropic.AuthenticationError) {
        authenticationFailed = true;
      }
      throw error;
    }

    const text = normalizeSummaryText(response);
    return text.length > 0 ? { kind: 'success', text } : { kind: 'degenerate', reason: 'empty' };
  };
}

/**
 * Judgment-specific eligibility (Boundaries & Constraints): a Node is
 * eligible only when its file is not in the current coverage-gap set AND it
 * has no persisted `NodeRecord.llmJudgment` yet — no regeneration path this
 * phase (mirrors Phase 1's own scoping; unlike summaries, there is no
 * judgment counterpart to `regenerateNodeSummary` yet).
 */
function isEligibleForJudgment(node: CodeMapNode, coverageGapFiles: ReadonlySet<string>): boolean {
  if (coverageGapFiles.has(node.file)) {
    return false;
  }
  return getNodeRecord(node.id)?.llmJudgment === undefined;
}

/** Batches individual completions into `onProgress` posts (Always/AD-8) — mirrors `summary-generator.ts`'s own `createProgressBatcher`. */
function createProgressBatcher(onProgress: (updated: LlmJudgmentProgressUpdate[]) => void) {
  let pending: LlmJudgmentProgressUpdate[] = [];
  let timer: ReturnType<typeof setTimeout> | null = null;

  function flush(): void {
    if (timer) {
      clearTimeout(timer);
      timer = null;
    }
    if (pending.length === 0) {
      return;
    }
    const batch = pending;
    pending = [];
    onProgress(batch);
  }

  function add(update: LlmJudgmentProgressUpdate): void {
    pending.push(update);
    if (pending.length >= PROGRESS_FLUSH_BATCH_SIZE) {
      flush();
      return;
    }
    timer ??= setTimeout(flush, PROGRESS_FLUSH_INTERVAL_MS);
  }

  return { add, flush };
}

export interface GenerateJudgmentsOptions {
  /** Absolute, OS-native path to the project root — source is read relative to this. */
  projectRoot: string;
  /** The Code Map's Nodes (already-fetched) — filtered down to the eligible subset here. */
  nodes: CodeMapNode[];
  /** POSIX-relative paths (matching `CodeMapNode.file`) currently in the index's coverage gap set. */
  coverageGapFiles: ReadonlySet<string>;
  /** The pluggable per-Node judgment step — built by the caller (index.ts) via `createLocalJudge`/`createCloudJudge`. */
  judge: SummarizeFn;
  /** The backend/model name persisted into `NodeRecord.llmJudgment.model` for every Node this run successfully judges. */
  modelName: string;
  /** Fired with each batched group of completions (Always/AD-8: never one call per Node). */
  onProgress: (updated: LlmJudgmentProgressUpdate[]) => void;
  /**
   * Checked before every merge-write/progress post — lets a caller (index.ts)
   * discard a superseded run's results, mirroring
   * `GenerateSummariesOptions.isSuperseded`. Defaults to always-current when
   * omitted.
   */
  isSuperseded?: () => boolean;
}

/**
 * Generates one-sentence chief-risk-factor judgments for every eligible Node
 * (FR8), enqueued onto `sharedSummaryQueue` — never a second `PQueue` (Always,
 * AD-8) — merge-writing each result via `mergeNodeRecord` and batching
 * progress via `onProgress`. Resolves once every eligible Node has been
 * attempted (success or logged-and-skipped failure) — callers run this in the
 * background (never awaited alongside the Code Map response).
 *
 * A local/cloud call failure, timeout, or degenerate (empty) response writes
 * nothing and produces no signal this round (Always) — mirrors
 * `generateSummaries`'s own catch-and-skip framing exactly, minus the
 * hardware-advisory tracking and staleness-baseline capture this phase's
 * Never constraint excludes.
 */
export async function generateJudgments(options: GenerateJudgmentsOptions): Promise<void> {
  const {
    projectRoot,
    nodes,
    coverageGapFiles,
    judge,
    modelName,
    onProgress,
    isSuperseded = () => false,
  } = options;

  const eligible = nodes.filter((node) => isEligibleForJudgment(node, coverageGapFiles));
  if (eligible.length === 0 || isSuperseded()) {
    return;
  }

  // The shared module-level queue (summary-generator.ts) — never a fresh
  // `PQueue` scoped to this call (Always: "no second `PQueue`").
  const queue = sharedSummaryQueue;
  const batcher = createProgressBatcher((updated) => {
    if (isSuperseded()) {
      return;
    }
    onProgress(updated);
  });

  await Promise.all(
    eligible.map((node) =>
      queue.add(async () => {
        if (isSuperseded()) {
          return;
        }
        let outcome: SummarizeOutcome;
        try {
          outcome = await judge(node, projectRoot);
        } catch (error) {
          console.error(
            `[graph-service] judgment generation failed for ${node.id}: ${
              error instanceof Error ? error.message : String(error)
            }`,
          );
          return;
        }
        if (isSuperseded()) {
          return;
        }
        if (outcome.kind === 'unreadable' || outcome.kind === 'degenerate') {
          // Never a partial/wrong judgment persisted, never a signal this
          // round (Always) — the Node simply stays without a persisted
          // judgment for this session.
          return;
        }
        try {
          mergeNodeRecord(node.id, {
            llmJudgment: {
              text: outcome.text,
              model: modelName,
              generatedAt: new Date().toISOString(),
            },
          });
        } catch (error) {
          console.error(
            `[graph-service] failed to persist judgment for ${node.id}: ${
              error instanceof Error ? error.message : String(error)
            }`,
          );
          return;
        }
        batcher.add({ id: node.id, judgment: outcome.text });
      }),
    ),
  );
  batcher.flush();
}
